const UPDATE_COUNTER='UPDATE_COUNTER'
const FETCH_USER_REQUEST='FETCH_USER_DATA'
const REQUEST_FAIL='FETCH_REQUEST_FAIL'
const REQUEST_SUCCESS='FETCH_REQUEST_SUCCESS'
export {FETCH_USER_REQUEST,REQUEST_FAIL,REQUEST_SUCCESS,UPDATE_COUNTER}
