const PRODUCE_ITEM = 'PRODUCE_ITEM'
const CONSUME_ITEM = 'CONSUME_ITEM'
const SHELL_BOOKS = 'SHELL_BOOKS'
const BYU_BOOKS = 'BUY_BOOKS'
module.exports ={PRODUCE_ITEM,CONSUME_ITEM,SHELL_BOOKS,BYU_BOOKS}